# server listen port
server_port: 80
# db_user:password@tcp(localhost:3306)/my_db
dsn: "root:123456@tcp(192.168.137.10:3306)/domaincheckerdb"
# json web token sign key
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
# json web token sign expiration in hours
jwt_expiration: 720